feat: lazygit config added

diff --git a/.local/scripts/mon b/.local/scripts/mon
--- a/.local/scripts/mon
+++ b/.local/scripts/mon
@@ -1,7 +1,9 @@
 #!/usr/bin/env bash
 
+SCREENLAYOUT_DIR="$HOME/.screenlayout"
+
 if [[ -z $1 ]]; then
-    options=("Default" "Office" "Home" "HomeTriple")
+    options=($(ls "$SCREENLAYOUT_DIR"/*.sh | xargs -n1 basename | sed 's/\.sh$//'))
     selected_option=$(printf '%s\n' "${options[@]}" | fzf --prompt="Select monitor configuration: ")
     if [[ -z $selected_option ]]; then
         exit 0
@@ -10,23 +12,12 @@ else
     selected_option=$1
 fi
 
-case $selected_option in
-    "Default")
-        xrandr --output eDP --mode 1920x1200 --pos 0x0 --rotate normal --output HDMI-A-0 --off --output DisplayPort-0 --off --output DisplayPort-1 --off
-        ;;
-    "Office")
-        xrandr --output HDMI-1 --primary --mode 2560x1440 --pos 0x0 -r 143.91 --rotate normal --output eDP-1 --mode 1920x1200 --pos 2560x0 -r 60.00 --rotate normal
-        ;;
-    "Home")
-        xrandr --output eDP --off --output HDMI-A-0 --mode 1920x1080 --primary --rate 60 --pos 0x0 --rotate normal --output DisplayPort-0 --mode 1920x1080 --rate 120 --pos 1920x0 --rotate normal
-        ;;
-    "HomeTriple")
-        xrandr --output eDP --mode 1920x1200 --pos 0x0 --rotate normal --output HDMI-A-0 --primary --mode 1920x1080 --pos 1920x0 --rotate normal --output DisplayPort-0 --mode 1920x1080 --pos 3840x0 --rotate normal --output DisplayPort-1 --off
-        ;;
-    *)
-        echo "Invalid option: $selected_option"
-        exit 1
-        ;;
-esac
+script_path="$SCREENLAYOUT_DIR/${selected_option}.sh"
 
-leftwm-command SoftReload
+if [[ -f "$script_path" ]]; then
+    bash "$script_path"
+    leftwm-command SoftReload
+else
+    echo "Invalid option or script not found: $selected_option"
+    exit 1
+fi
